name: C/C++ CI

on:
  push:
    branches:
    - main
    - release/* 
  pull_request:
    branches:
    - main

jobs:
    firmware_build:
        name: Build Pico Memory tester
        runs-on: ubuntu-latest
        permissions:
            contents: read

        steps:
          - run: echo "🎉 Build was automatically triggered by a ${{ github.event_name }} event."
          - run: echo "🔎 Your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
          - name: Checkout
            uses: actions/checkout@v5

          - name: Build Pico Memory Tester
            id: build
            uses: samyarsadat/Pico-Build-Action@v1
            with:
                source_dir: "firmware"
                cmake_args: "-DCMAKE_BUILD_TYPE=Release"

          - name: Upload Build Artifacts
            uses: actions/upload-artifact@v4
            with:
                name: workspace_artifacts
                path: ${{steps.build.outputs.output_dir}}
